parameters:
#    class_central_mooc_tracker.example.class: ClassCentral\MOOCTrackerBundle\Example

services:
#    class_central_mooc_tracker.example:
#        class: %class_central_mooc_tracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
